### ISSUE TITLE
conversion

### ISSUE THREAD

**Issue by ounsen** [dragouf/CbrPdfConverter#4]
Hello i don't know how to contact you, I can't convert a 146MB pdf to cbz but i can with a 1 MB file. Is it normal ?

**Comment by ounsen** [comment]
Unknown encryption type R = 6

**Comment by rfog** [comment]
Hi! If PDF is encrypted or has a password or any other kind of DRM, it won't work as it is protected to not to be copied.

You could try to generate a new PDF printing the PDF into a virtual PDF printer o use any online service to "remove passwords" and use the result to generate the CBZ.

**Comment by ounsen** [comment]
yes! you are right it's working for another manga thank you !
